### ISSUE TITLE
No module named 'svmutil'

### ISSUE THREAD

**Issue by Niroznak** [ocampor/notebooks#10]
Hi,
i tried your code, and get this error "No module named 'svmutil'".
everything else working perfectly, until the last section of the actual scoring.
i couldn't find how to install this package.
which python version you used for it? 
i'm using 3.6, is there another package that could replace it?

**Comment by ocampor** [comment]
Hey! Thanks for noticing. You can install the package https://pypi.org/project/libsvm

You might need to slightly modify the code. Try installing the package and replacing the svm import with from libsvm import svmutil.

Let me know how it goes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ocampor** [comment]
@Niroznak I added the modification to the notebook, could you please confirm that this solves your problem?

**Comment by ocampor** [comment]
#close #10 due to inactivity

**Comment by Niroznak** [comment]
Hi,
sorry for the late response, but this still doesnt work for me, cant import svmutil.
i also tried import sklearn.svm.libsvm and then import from there, still no svmutil.

anyways thanks for the code and support, i`ll continue trying.
