### ISSUE TITLE
UnPickling error on Quality Notebook 

### ISSUE THREAD

**Issue by kikushiyo** [ocampor/notebooks#12]
Hello,

I tried to reproduce your notebook https://github.com/ocampor/notebooks/blob/master/notebooks/image/quality/brisque.ipynb and I am facing an issue to deserialize 'normalize.pickle'  :
![image](https://user-images.githubusercontent.com/11709810/70065177-f1b62c80-15ea-11ea-9548-538af45da317.png)

This is reproduced both in Python 3.6.8 and 3.7.5. Any idea ?

**Comment by ocampor** [comment]
It must be the file encoding.

**Comment by ocampor** [comment]
Closing because of lack of answer
