### ISSUE TITLE
Error while executing brisque.ipynb

### ISSUE THREAD

**Issue by suresh-s** [ocampor/notebooks#13]
Dear Ricardo,

I am exploring BRISQUE score using your code. 

I am getting following Errors when executing the file brisque.ipynb.

At **In [15]:**, i am getting below error message

```
----------------------------------------------------------------------
NameError                            Traceback (most recent call last)
<ipython-input-15-f12daf33adba> in <module>
      2 plt.rcParams["figure.figsize"] = 12, 11
      3 
----> 4 for name, coeff in coefficients.items():
      5     plot_histogram(coeff.ravel(), name)
      6 

NameError: name 'coefficients' is not defined
```

I am getting following error for **In [17]:**

```
----------------------------------------------------------------------
NameError                            Traceback (most recent call last)
<timed exec> in <module>

NameError: name 'brisque_features' is not defined
```

Even though it show error message, At section **In [18]:** shows output as "**out[18]: 4.9541572815704455**"
Could you help me to resolve this issue?

**Comment by ocampor** [comment]
Thanks for reporting the issue. I’ll take a look and let you know what is going on.

**Comment by ocampor** [comment]
I have double-checked the case. I suggest you to run the cells in order. If the problem persists, please provide me with more information like:
- Python version
- OS
