### ISSUE TITLE
Results out of range

### ISSUE THREAD

**Issue by icofalc** [ocampor/notebooks#16]
Hi @ocampor ,
i manage to get a working notebook from your implementation in google colab.
I did some tests on images of the kodak db, however when i try to compute the brisque score of this image:
http://www.cs.albany.edu/~xypan/research/img/Kodak/kodim04.png
it does give me -0.9774126600991906.
Is there any mistake? or do i have to understand that any result below 0 can be considered as 0?
Thanks.

**Comment by ocampor** [comment]
Yes, you might consider that below 0 is 0. The reason is that the picture of the input comes from a different population of the ones used to train the model. You can re-train the model to get results that suit better your needs.

**Comment by icofalc** [comment]
Sweat, thank you
