### ISSUE TITLE
Not able to reproduce results

### ISSUE THREAD

**Issue by DecentMakeover** [ocampor/notebooks#3]
Hi 
@ocampor 
I ran your notebook as is, But my final score comes out to be 155.70740067882858 not 
4.954157281562374. Any idea why there might be such discrepancy.

EDIT-

Also i realise the final image quality score varies every time i run it.Really not sure what is happening , i ran it on the docker and it runs fine, to be on the safe side i froze the docker envoirnment and installed all the packages in my system, still no progress.

 
Thanks in advance.

**Comment by lukegarland** [comment]
I am also having this issue as well.

**Comment by DecentMakeover** [comment]
It should be a python version issue

**Comment by lukegarland** [comment]
I see. It works running it in python 3, but unfortunately, my current project requires the use of python 2.7, so it would be nice to have it working in 2.7. Not sure where the script breaks with 2.7.

**Comment by DecentMakeover** [comment]
Build the dictionary yourself , in the part where it is using the collections module

On 14-May-2019, at 1:49 AM, Luke Garland <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. It works running it in python 3, but unfortunately, my current project requires the use of python 2.7, so it would be nice to have it working in 2.7. Not sure where the script breaks with 2.7.

**Comment by lukegarland** [comment]
What do you mean by that?

**Comment by ocampor** [comment]
@DecentMakeover it is hard to define the cause of your problem. There are several packages that are involved in the calculation, so it might be cause by a version difference or that you replaced a function. It is not an stochastic algorithm so the results shouldn't vary. I would recommend to use the Dockerfile as you mention you are doing.
