### ISSUE TITLE
Trouble opening normalize.pickle

### ISSUE THREAD

**Issue by driesendert** [ocampor/notebooks#4]
Hello,

I am struggling with a recurring error message when trying to run the final kernel. (see image)
![image](https://user-images.githubusercontent.com/43064968/54984625-8aea6900-4faf-11e9-9a84-5508b18e75f6.png)

I believe the source of the issue is when the scale_features function attempts to open and read the normalize.pickle file. Do you know what I can do to solve this?

Kind regards

**Comment by ocampor** [comment]
I would recommend you to use the Docker included in the repository to reproduce the results.
