### ISSUE TITLE
Unable to produce results

### ISSUE THREAD

**Issue by aastha19** [ocampor/notebooks#5]
On trying to calculate the brisque score an error occurs as follows:

![image](https://user-images.githubusercontent.com/14852345/61686532-7e97d200-ad3d-11e9-88be-e2f4411b56f3.png)

**Comment by ocampor** [comment]
You can use this package https://github.com/ocampor/image-quality

**Comment by aastha19** [comment]
> You can use this package https://github.com/ocampor/image-quality

This package cannot be installed.

**Comment by ocampor** [comment]
@aastha19 please create an issue with the description of your problem and I will try to fix. Please add all the details.

#close

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
