### ISSUE TITLE
how to train a brisque_svm.txt on my own dataset

### ISSUE THREAD

**Issue by kli017** [ocampor/notebooks#6]
Hello thanks for the awesome tutorial of IQA. I'm doing IQA on some Document images. After I run your code on some images. I found that for some clean images there MSCN distribution are very similar but the final brisque score are very high(more than 70). I was wondering how to train a new brisque_svm on my own dataset or how to direct asses the image quality by the  pair product coefficients. Thank for any advice!

**Comment by ocampor** [comment]
You can try the functions in this package https://github.com/ocampor/image-quality to calculate the feature vector for your pictures.

**Comment by kli017** [comment]
@ocampor thanks for the reply. I already extracted the feature vector of my images. If I want train with libsvm how many classes should I set and what is the label of each class?  simply 2 classed with +1 and -1?

**Comment by ocampor** [comment]
The model is a SVR that maps the vector with feature to an subjective quality score. I recommend you to read the methodology behind the creation of the benchmark TID2008 
https://pdfs.semanticscholar.org/6dd3/7b57f3391b438fa588f98a1c2067365ae5ca.pdf

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
