### ISSUE TITLE
svmutil gen_svm_nodearray

### ISSUE THREAD

**Issue by kli017** [ocampor/notebooks#7]
x, idx = svmutil.gen_svm_nodearray(scaled_brisque_features, isKernel=(model.param.kernel_type == svmutil.PRECOMPUTED))
AttributeError: 'NoneType' object has no attribute 'param'

**Comment by Anaga352** [comment]
> x, idx = svmutil.gen_svm_nodearray(scaled_brisque_features, isKernel=(model.param.kernel_type == svmutil.PRECOMPUTED))
> AttributeError: 'NoneType' object has no attribute 'param'

Hi, Got the Same Error. Can you pls help..?
